server/.gitignore, server/build.gradle
=> :tada: dev PR

.github/workflows/gradle-publish.yml, server/.gitignore, server/Dockerfile, server/Dockerfile_client, server/src/main/resources/application.properties, server/src/main/resources/application.yml
=> [BE-000] yml 파일수정

server/build.gradle, server/src/main/java/com/seb44main011/petplaylist/domain/music/controller/MusicController.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/controller/publicMusicController.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/dto/MusicDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/entity/Music.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/mapper/MusicMapper.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/repository/MusicRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/service/MusicService.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/controller/PlaylistController.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/dto/PlaylistDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/entity/PersonalPlayList.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/mapper/PlaylistMapper.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/repository/PlaylistRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/PlaylistService.java, server/src/main/java/com/seb44main011/petplaylist/global/error/ExceptionCode.java, server/src/main/resources/application.yml, server/src/test/java/com/seb44main011/petplaylist/domain/music/controller/MusicControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/stub/MusicTestData.java
ㅡmusic, playlist 디렉토리 구조 및 music 테스트코드 추가
-  music, playlist 디렉토리 구조 추가
-  music 테스트코드 추가
- Stub 데이터 추가
#7
=> [PL-BE-000] 디렉토리 구조 및 테스트코드 추가

server/src/main/java/com/seb44main011/petplaylist/domain/member/entity/Member.java, server/src/main/java/com/seb44main011/petplaylist/domain/member/service/MemberService.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/dto/MusicDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/entity/Music.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/service/MusicService.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/controller/ApiPlaylistController.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/entity/compositeKey/MusicListId.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/entity/entityTable/MusicList.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/entity/entityTable/PersonalPlayList.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/mapper/MusicListMapper.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/repository/MusicListRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/repository/PlaylistRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/MusicListService.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/PlaylistService.java, server/src/main/resources/application.yml
개인플레이 리스트 기능 추가
- 좋아요 요청시  개인 플레이리스트에 추가된다
- 좋아요 삭제 요청시 개인 플레이리스트에서 삭제된다
#49 #6
=> [PL_BE_000] 개인플레이 리스트 기능 추가

server/src/main/java/com/seb44main011/petplaylist/domain/member/controller/MemberController.java, server/src/main/java/com/seb44main011/petplaylist/domain/member/service/MemberService.java, server/src/test/java/com/seb44main011/petplaylist/domain/member/controller/MemberControllerTest.java
회원탈퇴 기능 구현 완료
- 회원탈퇴 기능 구현에 필요한 코드 추가
- 회원탈퇴 테스트 코드 추가 및 API  문서화
#18
=> [MS_BE_005] 회원탈퇴 기능 구현 완료

server/src/main/java/com/seb44main011/petplaylist/domain/member/controller/MemberController.java, server/src/main/java/com/seb44main011/petplaylist/domain/member/dto/MemberDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/member/entity/Member.java, server/src/main/java/com/seb44main011/petplaylist/domain/member/service/MemberService.java, server/src/main/java/com/seb44main011/petplaylist/global/error/ExceptionCode.java, server/src/test/java/com/seb44main011/petplaylist/domain/member/controller/MemberControllerTest.java
비밀번호 검증 기능 추가
- 비밀번호 검증 기능 추가에 따른 코드 리팩토링
- 테스트 코드 리팩토링 및 API 문서화
#18
=> [MS_BE_005] 회원탈퇴 기능 리팩토링

server/src/main/java/com/seb44main011/petplaylist/domain/comment/dto/CommentDto.java, server/src/main/java/com/seb44main011/petplaylist/global/error/ExceptionCode.java, server/src/test/java/com/seb44main011/petplaylist/domain/comment/controller/CommentControllerTest.java
댓글 수정 테스트 완료
댓글 CRUD patch 테스트 완료
CM_BE_002
=> :necktie: 댓글 수정 테스트 완료

client/src/App.tsx, client/src/components/SideBar.tsx, client/src/pages/Tags.tsx
✅ feat: SideBar 기능 작업중..
✅ feat: SideBar 기능 작업중..
=> ✅ feat: SideBar 기능 작업중..

server/.gitignore, server/src/main/java/com/seb44main011/petplaylist/domain/music/mapper/MusicMapper.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/service/MusicService.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/controller/ApiPlaylistController.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/dto/PlaylistDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/mapper/PlaylistMapper.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/repository/MusicListRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/MusicListService.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/PlaylistService.java, server/src/main/java/com/seb44main011/petplaylist/global/advice/GlobalExceptionAdvice.java, server/src/main/java/com/seb44main011/petplaylist/global/config/WebConfig.java, server/src/main/java/com/seb44main011/petplaylist/global/utils/PageNationCreator.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/controller/MusicControllerTest.java
개인 플레이 리스트 조회 추가 및 서버 포트 확장
- 개인 플레이 리스트 조회 기능 추가
- 페이지 네이션 공용 컴포넌트 추가
- 5173 포트 허용
#51 #43
=> [PL-BE-001] 개인 플레이 리스트 조회 추가

server/build.gradle, server/src/main/java/com/seb44main011/petplaylist/domain/music/entity/Music.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/service/MusicService.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/controller/ApiPlaylistController.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/controller/PublicPlaylistController.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/dto/PlaylistDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/mapper/PlaylistMapper.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/MusicListService.java, server/src/main/java/com/seb44main011/petplaylist/global/common/MultiResponseDto.java, server/src/main/java/com/seb44main011/petplaylist/global/utils/PageNationCreator.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/stub/TestData.java, server/src/test/java/com/seb44main011/petplaylist/domain/playlist/ApiPlayListControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/playlist/PublicPlayListControllerTest.java
전체 플레이 리스트 조회(조회수 기준 정렬) 기능 추가 및 코드 리펙토링
- 전체 플레이 리스트 조회 기능 추가
- 조회수 기준으로 정렬함
- Api응답 dto 통합
- 전체 플레이 리스트 조회 테스트 코드 및 스웨거 문서화 추가
#3
=> [PL_BE001] 전체 플레이 리스트 조회(조회수 기준 정렬) 기능 추가

server/src/main/java/com/seb44main011/petplaylist/domain/comment/controller/CommentController.java, server/src/test/java/com/seb44main011/petplaylist/domain/comment/controller/CommentControllerTest.java
=> :necktie: 댓글 조회 테스트 완료

client/index.html, client/src/components/commons/Share.tsx, client/src/main.tsx, client/src/pages/Login.tsx, client/src/pages/SignUp.tsx, client/src/utils/Check.ts, client/src/utils/Url.ts
Naver OAuth 작업 및 정규식 수정
- 네이버 OAuth 두 개의 버튼으로 테스트 중
- 비밀번호 정규식 분리(MinLength, MaxLength, 영문자1+숫자1)
=> [Login/naver] Naver OAuth 작업 및 정규식 수정

server/src/main/java/com/seb44main011/petplaylist/domain/member/auth/config/SecurityConfiguration.java
=> :ambulance: 클라이언트에서 토큰 안보이는 에러 해결

server/build/resources/main/static/docs/open-api-3.0.1.json, server/src/main/java/com/seb44main011/petplaylist/domain/member/auth/filter/JwtVerificationFilter.java, server/src/main/java/com/seb44main011/petplaylist/domain/member/dto/MemberDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/member/mapper/MemberMapper.java
=> fix: 마이페이지 오류 해결

client/src/components/DeleteModal.tsx, client/src/pages/Edit.tsx
=> feat:mypage

client/src/components/CommentSection.tsx
=> 🐛feat:comment 

server/src/main/java/com/seb44main011/petplaylist/domain/member/auth/handler/oauthHandler/OAuth2SuccessHandler.java
=> ♻️ OAuth2 리스폰스 memberId 추가

server/src/main/java/com/seb44main011/petplaylist/domain/member/auth/handler/oauthHandler/OAuth2SuccessHandler.java
Reverts codestates-seb/seb44_main_011#121
=> Revert "♻️ OAuth2 리스폰스 memberId 추가"

server/src/main/java/com/seb44main011/petplaylist/domain/member/auth/handler/oauthHandler/OAuth2SuccessHandler.java
Reverts codestates-seb/seb44_main_011#122
=> Revert "Revert "♻️ OAuth2 리스폰스 memberId 추가""

server/src/main/java/com/seb44main011/petplaylist/domain/music/controller/admin/AdminMusicController.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/controller/admin/MusicFileController.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/dto/MusicDto.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/mapper/MusicMapper.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/repository/MusicRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/service/mainService/MusicService.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/service/storageService/S3Service.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/service/storageService/StorageService.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/util/MP3DurationCalculator.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/repository/MusicListRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/MusicListService.java, server/src/main/java/com/seb44main011/petplaylist/global/error/ExceptionCode.java, server/src/main/java/com/seb44main011/petplaylist/global/utils/UriCreator.java, server/src/main/resources/application.yml, server/src/test/java/com/seb44main011/petplaylist/domain/music/controller/MusicAdminControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/controller/MusicFileControllerTest.java
관리자 페이지 api 추가
- 음원 파일 삭제, 수정 기능 추가
- 관리자 권한이 없을 경우 수정 불가능
=> [BE_AD000] 관리자 페이지 api 추가

client/src/App.tsx, client/src/components/EditProfile.tsx, client/src/components/ImageModal.tsx, client/src/components/MypageInfo.tsx, client/src/components/SideNav.tsx, client/src/pages/MyPage.tsx, client/src/pages/Search.tsx, client/src/utils/Url.ts
✅ feat: 프로필이미지, 닉네임 변경가능 , 이미지모달 8개로 추가
=> ✅ feat: 프로필이미지, 닉네임 변경가능 , 이미지모달 8개로 추가

server/src/main/java/com/seb44main011/petplaylist/domain/member/controller/MemberController.java, server/src/test/java/com/seb44main011/petplaylist/domain/member/controller/MemberControllerTest.java
=> api: 마이페이지 API Path 변경

server/src/main/java/com/seb44main011/petplaylist/domain/member/mapper/MemberMapper.java
=> :bug: 마이페이지 리스폰스 버그 해결

client/src/components/MusicList.tsx, client/src/components/MypageInfo.tsx, client/src/pages/Home.tsx, client/src/pages/MyList.tsx
=> 🐛 feat:admin

server/src/test/java/com/seb44main011/petplaylist/domain/member/controller/MemberControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/member/stub/MemberTestData.java
=> test: 테스트 코드 추가

client/src/pages/Search.tsx
=> ✅feat:search 

client/src/components/MusicList.tsx, client/src/components/MypageInfo.tsx
=> 🐛feat:admin 

client/src/components/ImageModal.tsx, client/src/components/MusicList.tsx, client/src/pages/MyPage.tsx, client/src/pages/Search.tsx
=> ✅ Build Success

.github/workflows/docker-image.yml, server/Dockerfile, server/build.gradle, server/build/resources/main/static/docs/open-api-3.0.1.json, server/src/docs/asciidoc/index.adoc, server/src/main/java/com/seb44main011/petplaylist/domain/member/auth/config/SecurityConfiguration.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/controller/admin/AdminMusicController.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/controller/admin/MusicFileController.java, server/src/main/java/com/seb44main011/petplaylist/domain/music/entity/Music.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/controller/ApiPlaylistController.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/repository/MusicListRepository.java, server/src/main/java/com/seb44main011/petplaylist/domain/playlist/service/MusicListService.java, server/src/main/resources/static/docs/open-api-3.0.1.json, server/src/test/java/com/seb44main011/petplaylist/domain/comment/controller/CommentControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/controller/MusicAdminControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/controller/MusicApiControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/controller/MusicFileControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/music/stub/TestData.java, server/src/test/java/com/seb44main011/petplaylist/domain/playlist/apiTest/ApiFieldDescriptor.java, server/src/test/java/com/seb44main011/petplaylist/domain/playlist/apiTest/ApiPlayListControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/domain/playlist/publicTest/PublicPlayListControllerTest.java, server/src/test/java/com/seb44main011/petplaylist/global/MusicFieldDescriptor.java, server/src/test/java/com/seb44main011/petplaylist/global/SecurityWithMockUser.java
전체 플레이 리스트 리펙토링
전체 플레이 리스트 리펙토링
#27
=> [PL_BE000] 전체 플레이 리스트 리펙토링

client/src/components/EditProfile.tsx, client/src/components/MypageInfo.tsx, client/src/components/SideNav.tsx, client/src/pages/Login.tsx, client/src/pages/Oauth.tsx
=> [Dev] 에러 처리

client/src/components/MusicList.tsx, client/src/utils/saveNewToken.ts
=> 🐛 글자 오류 수정

client/src/components/EditProfile.tsx
=> 🐛 EditProfile 에러 메시지 출력

client/src/components/DeleteModal.tsx, client/src/components/EditProfile.tsx, client/src/components/SideNav.tsx, client/src/pages/Login.tsx, client/src/pages/SignUp.tsx
=> 🐛 에러 처리 및 signup->login

client/src/pages/SignUp.tsx, package-lock.json
=> 🐛 Build error 수정

client/src/components/CommentSection.tsx, client/src/components/DeleteModal.tsx, client/src/components/EditProfile.tsx, client/src/components/ImageModal.tsx, client/src/components/MusicList.tsx, client/src/components/MypageInfo.tsx, client/src/pages/Search.tsx, client/src/types/Comment.ts, client/src/utils/Check.ts
이미지 불러오기 수정, 정규식 수정, accessToken 재발급 로직 추가
=> Dev - 이미지 불러오기 수정, 정규식 수정, accessToken 재발급 로직 추가
